### ISSUE TITLE
Quaterly Press Release

### ISSUE THREAD

**Issue by Mel-Marsollier** [eea-oasis/baseline-outreach#10]
Acceptance Criteria:

Quaterly Press Release

**Comment by Mel-Marsollier** [comment]
Look with Samrat if there is an idea

**Comment by Mel-Marsollier** [comment]
Marc Huddle and Samrat to work with Lilian Guinther on Excel release

**Comment by GoldenBit0** [comment]
Should create a process for this that involves tracking in issue.
